// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrlShortener.Infrastructure.Context;

#nullable disable

namespace UrlShortener.Infrastructure.Migrations
{
    [DbContext(typeof(ShortenDbContext))]
    partial class ShortenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrlShortener.Domain.Shorten.ShortenUrls.ShortenUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsExpiring")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expiring");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("long_url");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("short_url");

                    b.HasKey("Id")
                        .HasName("pk_shorten_urls");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_shorten_urls_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_shorten_urls_id");

                    b.ToTable("shorten_urls", "shorten");
                });

            modelBuilder.Entity("UrlShortener.Domain.Shorten.ShortenUrls.ShortenUrlTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("accessed_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("ShortenUrlId")
                        .HasColumnType("uuid")
                        .HasColumnName("shorten_url_id");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_short_url_tracks");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_short_url_tracks_code");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_short_url_tracks_id");

                    b.HasIndex("ShortenUrlId")
                        .HasDatabaseName("ix_short_url_tracks_shorten_url_id");

                    b.ToTable("short_url_tracks", "shorten");
                });
#pragma warning restore 612, 618
        }
    }
}
